### ISSUE TITLE
I can't write CSS in boring.

### ISSUE THREAD

**Issue by josheverett** [DynoSRC/boring#13]
You've literally ruined Christmas. When I make an app with `create-react-app` I can import CSS files into my react components and write regular CSS like a human being. When I use boring a puppy dies each time I write a new CSS object literal.

**Comment by ryanstevens** [comment]
This is false.  Make a css file, and import it like 

‘’’import from “mycss.css”’’’

**Comment by ryanstevens** [comment]
Closing as this has always been a feature of boring since boring was essentially a fork of CRNA (at one point in time at least).
